<?php
require_once __DIR__.'/config/db.php';
require_once __DIR__.'/lib/functions.php';

$item_id = (int)($_GET['item_id'] ?? 0);
if(!$item_id){ echo "Missing item"; exit; }

$sql = "SELECT oi.*,
               t.name as test_name, t.code, t.department as test_dept,
               o.id as order_id, o.order_date, o.ordering_doctor,
               p.first_name, p.middle_name, p.last_name, p.suffix, p.dob, p.sex, p.id as patient_id
        FROM order_items oi
        JOIN orders o ON o.id=oi.order_id
        JOIN patients p ON p.id=o.patient_id
        JOIN tests t ON t.id=oi.test_id
        WHERE oi.id=?";
$stmt = $pdo->prepare($sql); $stmt->execute([$item_id]); $r = $stmt->fetch();
if(!$r){ echo "Not found"; exit; }
?>
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Lab Report #<?= (int)$r['id'] ?></title>
    <link rel="stylesheet" href="assets/app.css">
    <style>
      :root{ --line:#d6dccf; }
      body{ background:#fff; margin:0; }
      .report{
        max-width:840px;
        margin:20px auto;
        background:#fff;
        padding:28px;
        border-radius:12px;
        position:relative;
        overflow:visible;
        box-shadow:0 1px 4px rgba(0,0,0,.06);
      }
      .report header{display:flex;gap:16px;align-items:center;border-bottom:2px solid var(--line);padding-bottom:12px;margin-bottom:12px}
      .report header img{width:56px;height:56px}
      .report h2{margin:0}
      .report table{width:100%}
      .report::before{
        content:"";
        position:absolute;
        inset:0;
        background:url('assets/logo.png') no-repeat center center;
        background-size: clamp(520px, 68%, 980px);
        opacity:.08;
        pointer-events:none;
      }
      .badge.danger{border-color:#f1c0c4;background:#ffe8ea;color:#a10f2b}
      @media print{
        @page { size: A4 portrait; margin: 12mm; }
        html, body{ height:auto; }
        body{ -webkit-print-color-adjust: exact; print-color-adjust: exact; margin:0 !important; background:#fff !important; }
        .noprint{ display:none !important; }
        .report{ width:auto; max-width:none; margin:0; padding:12mm; border-radius:10px; box-shadow:none; page-break-inside: avoid; break-inside: avoid; }
        .report::before{ inset:8mm; background-size: contain; opacity:.14; }
      }
    </style>
  </head>
  <body>
    <div class="report card">
      <header>
        <img src="assets/logo.png" alt="logo">
        <div>
          <h2>Evergreen Medical Hospital — Laboratory Report</h2>
          <div class="meta">Order #<?= (int)$r['order_id'] ?> · Item #<?= (int)$r['id'] ?> · <?= h($r['order_date']) ?></div>
        </div>
        <div style="margin-left:auto" class="noprint">
          <button class="btn small" onclick="window.print()">Print</button>
        </div>
      </header>

      <div class="grid cols-2">
        <div>
          <div class="meta"><strong>Patient:</strong> <?= h(format_name_row($r)) ?> (ID#<?= (int)$r['patient_id'] ?>)</div>
          <div class="meta"><strong>Sex/DOB:</strong> <?= h($r['sex']) ?> · <?= h($r['dob']) ?></div>
          <div class="meta"><strong>Doctor:</strong> <?= h($r['ordering_doctor']) ?></div>
        </div>
        <div>
          <div class="meta"><strong>Test:</strong> <?= h($r['code'].' — '.$r['test_name']) ?></div>
          <div class="meta"><strong>Test Dept:</strong> <?= h($r['test_dept']) ?></div>
          <div class="meta"><strong>Status:</strong> <?= status_badge($r['status']) ?></div>
        </div>
      </div>

      <hr class="sep">

      <table class="table">
        <thead><tr><th>Result</th><th>Unit</th><th>Reference Range</th><th>Updated</th></tr></thead>
        <tbody>
          <tr>
            <td><?= h($r['result_value']) ?> <?= $r['abnormal_flag']?'<span class="badge warn">abnormal</span>':'' ?></td>
            <td><?= h($r['result_unit']) ?></td>
            <td><?= h($r['reference_range']) ?></td>
            <td><?= h($r['updated_at']) ?></td>
          </tr>
        </tbody>
      </table>

      <div class="meta" style="margin-top:12px">Generated by Evergreen LIS. This report is for clinical use only.</div>
    </div>
  </body>
</html>
